### ISSUE TITLE
Error when watched directory contains subdirectories

### ISSUE THREAD

**Issue by kentor** [Kureev/browserify-react-live#12]
Repro:

Add some directory under the `components` folder in the first example.

```
├── components
│   ├── MyComponent.js
│   └── __tests__
```

```
❯ npm start

> example@1.0.0 start /Users/kenneth/stuff/browserify-react-live/examples/01 - Basic
> ./scripts/run

Starting up http-server, serving . on: http://0.0.0.0:8080
Hit CTRL-C to stop the server
/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-server/index.js:53
      throw e;
            ^
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:552:19)
    at Object.fs.readFileSync (fs.js:384:28)
    at Object.transformFileSync (/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-server/node_modules/babel/node_modules/babel-core/lib/api/node.js:137:54)
    at iterateFiles (/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-server/index.js:51:22)
    at Array.map (native)
    at runServer (/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-server/index.js:48:25)
    at Object.<anonymous> (/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-server/bin/cmd.js:17:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by Kureev** [comment]
Fixed in `0.4.2` of `browserify-patch-server`
