### ISSUE TITLE
Error when browserify-patch-server argument has ./

### ISSUE THREAD

**Issue by kentor** [Kureev/browserify-react-live#13]
In the first example, change the follow in `scripts/run`

``` diff
 #!/bin/bash
 node_modules/.bin/watchify index.js -o dist/bundle.js &
-node_modules/.bin/bfps components/* &
+node_modules/.bin/bfps ./components/* &
 node_modules/.bin/http-server . &
 wait
```

With a client connected, making a change will error

```

Starting up http-server, serving . on: http://0.0.0.0:8080
Hit CTRL-C to stop the server
ℹ [BDS:SYSTEM] [17:50:19] Patch server has been started on port 8081
ℹ [BDS:SYSTEM] [17:50:25] File components/MyComponent.js has been changed
ℹ [BDS:SYSTEM] [17:50:33] File components/MyComponent.js has been changed
/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-server/makeP
atch.js:9
    })[0].content;
         ^
TypeError: Cannot read property 'content' of undefined
    at calculateDiff (/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browser
ify-patch-server/makePatch.js:9:10)
    at composeWrapper (/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browse
rify-patch-server/compose.js:6:24)
    at processFile (/Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserif
y-patch-server/index.js:119:50)
    at /Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-serve
r/node_modules/babel/node_modules/babel-core/lib/api/node.js:125:5
    at fs.js:334:14
    at /Users/kenneth/stuff/browserify-react-live/examples/01 - Basic/node_modules/browserify-patch-serve
r/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by Kureev** [comment]
Hi @kentor! Sure, if you change watching folder to the folder which doesn't exist, you will receive this message. I'll change this error message to more informative one. Thanks for you efforts!

**Comment by Kureev** [comment]
More informative error message has been added in `0.4.2` of `browserify-patch-server`
